<a href="https://colab.research.google.com/github/Raffi38321/pm-turi2-preprocessing-MuhammadRaffi/blob/main/PM_P4_MuhammadRaffi_2488010046.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Langkah Praktikum

In [33]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    'nama': ['Andi', 'Budi', 'Citra', 'Deni', 'Eka'],
    'usia': [20, 21, np.nan, 23, 25],
    'pendapatan': [3000000, np.nan, 4500000, 5000000, 5500000],
    'membeli': ['Ya', 'Tidak', 'Ya', np.nan, 'Ya'],
    'pendidikan': ['SMA', 'S1', 'SMA', 'S2', np.nan],
    'kota':['jakarta','jakarta','cirebon','bogor','garut']
})

In [34]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].median())

In [35]:
X = df.drop(columns=['membeli'])
y = df['membeli']

In [36]:
X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2}) # ordinal
X = pd.get_dummies(X, columns=['kota'], dtype=int) # nominal
y = y.map({'Tidak':0,'Ya':1})

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
X, y, test_size=0.3, random_state=42)

In [38]:
from sklearn.preprocessing import StandardScaler
num = ['usia','pendapatan','pendidikan']
sc = StandardScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num]) # cegah data leakage

## Latihan Mandiri

### 1. ganti usia menjadi mean

In [39]:
df['usia'] = df['usia'].fillna(df['usia'].median())
df.head()

    nama  usia  pendapatan membeli pendidikan     kota
0   Andi  20.0   3000000.0      Ya        SMA  jakarta
1   Budi  21.0   4750000.0   Tidak         S1  jakarta
2  Citra  22.0   4500000.0      Ya        SMA  cirebon
3   Deni  23.0   5000000.0     NaN         S2    bogor
4    Eka  25.0   5500000.0      Ya        NaN    garut

### 2. gunakan minmaxScaller sebagai ganti standardscaller tampilkan describe

In [40]:
from sklearn.preprocessing import MinMaxScaler
mn = MinMaxScaler()
X_train[num] = mn.fit_transform(X_train[num])
X_test[num] = mn.transform(X_test[num])

X_train.describe()

,usia,pendapatan,pendidikan,kota_bogor,kota_cirebon,kota_garut,kota_jakarta
count,3.000000,3.000000,3.000000,3.000000,3.000000,3.0,3.000000
mean,0.555556,0.583333,0.333333,0.333333,0.333333,0.0,0.333333
std,0.509175,0.520416,0.577350,0.577350,0.577350,0.0,0.577350
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,0.333333,0.375000,0.000000,0.000000,0.000000,0.0,0.000000
50%,0.666667,0.750000,0.000000,0.000000,0.000000,0.0,0.000000
75%,0.833333,0.875000,0.500000,0.500000,0.500000,0.0,0.500000
max,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000

### 3. Tambahkan kolom kategorikal baru dan terapkan one-hot encoding.

In [41]:
df['kota_kelahiran']=['jakarta','jakarta','cirebon','bogor','garut']
df = pd.get_dummies(
    df,
    columns=['kota_kelahiran'],
    dtype=int
)

df.head()

,nama,usia,pendapatan,membeli,pendidikan,kota,kota_kelahiran_bogor,kota_kelahiran_cirebon,kota_kelahiran_garut,kota_kelahiran_jakarta
0,Andi,20.0,3000000.0,Ya,SMA,jakarta,0,0,0,1
1,Budi,21.0,4750000.0,Tidak,S1,jakarta,0,0,0,1
2,Citra,22.0,4500000.0,Ya,SMA,cirebon,0,1,0,0
3,Deni,23.0,5000000.0,NaN,S2,bogor,1,0,0,0
4,Eka,25.0,5500000.0,Ya,NaN,garut,0,0,1,0

### 4.Jelaskan mengapa fit_transform pada latih tetapi hanya transform pada uji.

Karena data uji tidak boleh ikut memengaruhi proses pembelajaran/preprocessing dari data latih.

## Refleksi

### 1. Mengapa urutan 'split dulu, baru scaling' penting?

karena untuk mencegah informasi bocor

### 2. Kapan label encoding dan kapan one-hot encoding?

label encoding digunakan ketika data memiliki urutan/hierarki. one hot ketika data tidak memiliki urutan

### 3. Apa perbedaan normalisasi dan standardisasi?
normalisasi mengubah rentang nilai ke 0-1, standarisasi mengubah data hingga meannya 0 dan standar deviasinya 1